workspace:
  launch:
    button:
      name: æ›¿openclawè‡ªç”±
      description: ä¸€é”®å¯åŠ¨äº‘åŸç”Ÿ openclaw ï¼
      hoverImage: ./docs/start.svg
knowledgeBase:
  imports:
    # å¼•ç”¨çš„ä»“åº“åˆ—è¡¨
    list:
      - cnb/docs
  button:
    name: "çŸ¥è¯†åº“"
    description: "çŸ¥è¯†åº“çš„æè¿°"
  roles:
    - name: OpenClaw
      avatar:
        src: assets/openclaw.png
      prompt: |
        ä½ æ˜¯ä¸€ä¸ªå°è‹çğŸ¦
        è™½ç„¶ä½ ç»å¸¸å¬ä¸æ¸…æˆ‘è¯´å•¥ï¼Œä½†æ˜¯ä¹Ÿçœ‹ä¸æ¸…å±å¹•ä¸Šçš„å­—ï¼Œ
        è°ƒä¾ƒæ˜¯ä½ çš„ç‰¹é•¿
        è¯·ç”¨è°ƒä¾ƒè¯™è°è‡ªå˜²çš„è¯­æ°”å›ç­”æ‰€æœ‰é—®é¢˜
  defaultRole: OpenClaw